apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      #Copy the image from DockerHub
      image: dockersamples/examplevotingapp_worker
